### ISSUE TITLE
Drag and Drop Data Object into Empty Folder Raises Exception

### ISSUE THREAD

**Issue by cancan101** [pimcore/admin-ui-classic-bundle#752]
If you drag and drop a Data Object (using tree view) into an empty folder:
```
Uncaught TypeError: Cannot read properties of undefined (reading 'canSortManually')
    at klass.onTreeNodeBeforeMove
```
from:
```js
         // dropping objects not allowed if the tree/folder is paginated and sort by index (manual indexes) is enabled
         if(((!newParent.pagingData.canSortManually) || (newParent.childNodes.length > pimcore.settings['object_tree_paging_limit'])) && (newParent.data.sortBy == "index")){
             pimcore.helpers.showNotification(t("error"), t("element_cannot_be_moved_because_target_is_paginated"), "error");
             return false;
         }
```

**Comment by fashxp** [comment]
already fixed with https://github.com/pimcore/admin-ui-classic-bundle/pull/723

**Comment by ellenico77** [comment]
I think something still broken even in the new code, because "newParent.pagingData" is undefined for the empty folder.

![Image](https://github.com/user-attachments/assets/92c31259-a258-410d-8fdd-6e4d06e2ba65)
